import {
  ACADEMIC_UPDATED_EVENT,
  listRecordsBySemester,
  type AcademicRecord,
  type AcademicSemester,
} from "@/lib/academic-store";

const STUDYPLAN_KEY = "somagnus:academic:studyplan:v1";

export type StudyPlanTaskStatus = "pending" | "done";

export type StudyPlanTask = {
  id: string;
  semesterId: string;
  blockType: "partial" | "final" | "remedial";
  blockIndex: number | null;
  title: string;
  dueDate: string;
  status: StudyPlanTaskStatus;
  autoGenerated: boolean;
};

export type StudyPlanState = {
  tasks: StudyPlanTask[];
};

function uid(prefix: string) {
  return `${prefix}_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;
}

function parseJson<T>(raw: string | null, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

function dispatchUpdate() {
  if (typeof window === "undefined") return;
  window.dispatchEvent(new Event(ACADEMIC_UPDATED_EVENT));
}

export function loadStudyPlan(): StudyPlanState {
  if (typeof window === "undefined") return { tasks: [] };
  const raw = parseJson<StudyPlanState>(window.localStorage.getItem(STUDYPLAN_KEY), { tasks: [] });
  return { tasks: Array.isArray(raw.tasks) ? raw.tasks : [] };
}

function saveStudyPlan(state: StudyPlanState) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STUDYPLAN_KEY, JSON.stringify(state));
  dispatchUpdate();
}

export function toggleStudyPlanTask(taskId: string) {
  const state = loadStudyPlan();
  const next = state.tasks.map((task) =>
    task.id === taskId ? { ...task, status: task.status === "done" ? "pending" : ("done" as StudyPlanTaskStatus) } : task,
  );
  saveStudyPlan({ tasks: next });
}

export function deleteStudyPlanTask(taskId: string) {
  const state = loadStudyPlan();
  saveStudyPlan({ tasks: state.tasks.filter((task) => task.id !== taskId) });
}

export function addStudyPlanTask(input: Omit<StudyPlanTask, "id" | "status" | "autoGenerated">) {
  const state = loadStudyPlan();
  const task: StudyPlanTask = {
    id: uid("plan"),
    status: "pending",
    autoGenerated: false,
    ...input,
  };
  saveStudyPlan({ tasks: [...state.tasks, task] });
  return task;
}

function daysBefore(isoDateStr: string, days: number): string | null {
  const base = new Date(isoDateStr);
  if (Number.isNaN(base.getTime())) return null;
  base.setUTCDate(base.getUTCDate() - days);
  return base.toISOString().slice(0, 10);
}

function isFuture(isoDateStr: string, now = new Date()): boolean {
  const parsed = new Date(isoDateStr);
  if (Number.isNaN(parsed.getTime())) return false;
  return parsed.getTime() >= now.getTime() - 86_400_000;
}

export function generateStudyPlanForSemester(semester: AcademicSemester): StudyPlanTask[] {
  const records = listRecordsBySemester(semester.id);
  const evaluations = records.filter(
    (record): record is AcademicRecord => record.itemType === "evaluacion" && !!record.date,
  );
  const existing = loadStudyPlan().tasks;
  const existingAuto = new Set(
    existing.filter((task) => task.semesterId === semester.id && task.autoGenerated).map((task) => task.id),
  );

  const cleaned = existing.filter((task) => !existingAuto.has(task.id));
  const next: StudyPlanTask[] = [...cleaned];

  for (const evaluation of evaluations) {
    if (!isFuture(evaluation.date)) continue;
    const milestones: Array<{ label: string; offsetDays: number }> = [
      { label: "Estudio inicial", offsetDays: 10 },
      { label: "Repaso intermedio", offsetDays: 5 },
      { label: "Simulacro y repaso final", offsetDays: 1 },
    ];
    for (const milestone of milestones) {
      const dueDate = daysBefore(evaluation.date, milestone.offsetDays);
      if (!dueDate) continue;
      next.push({
        id: uid("plan"),
        semesterId: semester.id,
        blockType: evaluation.blockType,
        blockIndex: evaluation.blockIndex,
        title: `${milestone.label} · ${evaluation.title}`,
        dueDate,
        status: "pending",
        autoGenerated: true,
      });
    }
  }

  saveStudyPlan({ tasks: next });
  return next.filter((task) => task.semesterId === semester.id);
}

export function listStudyPlanForSemester(semesterId: string): StudyPlanTask[] {
  return loadStudyPlan().tasks
    .filter((task) => task.semesterId === semesterId)
    .sort((a, b) => a.dueDate.localeCompare(b.dueDate));
}
